In [1]:
from google.colab import drive
drive.mount('/content/drive')

#!wget https://zenodo.org/record/835510/files/part1_cropped.tar.gz -O /content/drive/MyDrive/icub_data/part1_cropped.tar.gz

Mounted at /content/drive

In [2]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 43.0 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.3.0

## Local Inference on GPU
Model page: https://huggingface.co/google/vit-base-patch16-224

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/google/vit-base-patch16-224)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏

In [3]:
# Load model directly
#from transformers import AutoImageProcessor, AutoModelForImageClassification

#processor = AutoImageProcessor.from_pretrained("google/vit-base-patch16-224")
#model = AutoModelForImageClassification.from_pretrained("google/vit-base-patch16-224")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

Rudimentary test

In [4]:
from transformers import ViTImageProcessor, ViTForImageClassification
from PIL import Image
import requests
import torch

url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
image = Image.open(requests.get(url, stream=True).raw)

processor = ViTImageProcessor.from_pretrained('google/vit-base-patch16-224')
model = ViTForImageClassification.from_pretrained('google/vit-base-patch16-224')

inputs = processor(images=image, return_tensors="pt")
outputs = model(**inputs)
logits = outputs.logits
##  Model predicts one of the 1000 ImageNet classes.
predicted_class_idx = logits.argmax(-1).item()
print("Predicted class:", model.config.id2label[predicted_class_idx])

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

Predicted class: Egyptian cat

Extract downloaded iCub dataset.

In [10]:

!rm -r /content/all_images /content/icub_dataset

!mkdir /content/all_images
!mkdir /content/icub_dataset
!ls /content/drive/MyDrive/modules_work/COMP34212/icub_data
!tar xf /content/drive/MyDrive/modules_work/COMP34212/icub_data/part1_cropped.tar.gz -C /content/icub_dataset/

part1_cropped.tar.gz  part3_cropped.tar.gz
part2_cropped.tar.gz  part4_cropped.tar.gz

In [12]:
import glob
import os
import shutil
import pandas as pd

images = glob.glob("/content/icub_dataset/**/*.jpg", recursive=True)

monolith_dir = "/content/all_images"

metadata = []


for img in images:

  #print(img)

  file_path_split = img.split('/')

  #print(file_path_split)

  label = file_path_split[4]

  filename = file_path_split[-1]

  new_filename = f"{label}_{filename}"

  print(new_filename)

  metadata = metadata + [{
      "file_name": new_filename,
      "label": label
  }]

  shutil.move(img, os.path.join(monolith_dir, new_filename))

In [13]:
!find /content/icub_dataset -iname "*jpg" -exec mv -t /content/all_images/ {} ';'

In [14]:
##  Remove old metadata.

!rm /content/all_images/metadata.csv

##  Write new metadata.

df = pd.DataFrame(metadata)

metadata_csv = os.path.join(monolith_dir, "metadata.csv")

include_header = not os.path.exists(metadata_csv)

df.to_csv(metadata_csv,
          mode='a',
          index=False,
          header=include_header)

rm: cannot remove '/content/all_images/metadata.csv': No such file or directory

In [15]:
#!sed -i 's/filename/file_name/g' /content/all_images/metadata.csv

!head /content/all_images/metadata.csv

!tail /content/all_images/metadata.csv

file_name,label
00002499.jpg,pencilcase
00002642.jpg,pencilcase
00002511.jpg,pencilcase
00002498.jpg,pencilcase
00002671.jpg,pencilcase
00002673.jpg,pencilcase
00002570.jpg,pencilcase
00002660.jpg,pencilcase
00002624.jpg,pencilcase
00002666.jpg,ringbinder
00002661.jpg,ringbinder
00002439.jpg,ringbinder
00002623.jpg,ringbinder
00002412.jpg,ringbinder
00002504.jpg,ringbinder
00002432.jpg,ringbinder
00002520.jpg,ringbinder
00002416.jpg,ringbinder
00002390.jpg,ringbinder

In [16]:
from datasets import load_dataset, ClassLabel

dataset = load_dataset("imagefolder", data_dir="/content/all_images/")

print(dataset["train"][0])

dataset["train"] = dataset["train"].class_encode_column("label")

Resolving data files:   0%|          | 0/9748 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/9748 [00:00<?, ?files/s]

Generating train split: 0 examples [00:00, ? examples/s]

{'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2745C6DEE0>, 'label': 'pencilcase'}

Casting to class labels:   0%|          | 0/194918 [00:00<?, ? examples/s]

In [17]:
print(dataset["train"][0])

{'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D276834F200>, 'label': 3}

In [19]:
ds_split = dataset["train"].train_test_split(
    test_size=0.2,
    seed=6948566879846,
    stratify_by_column="label"
)

####  **iCub World dataset categories**

PART1: book, cellphone, mouse, pencilcase, ringbinder.

PART2: hairbrush, hairclip, perfume, sunglasses, wallet.

PART3: flower, glass, mug, remote, soapdispenser.

PART4: bodylotion, ovenglove, sodabottle, sprayer, squeezer.

####  **ImageNet dataset categories**

ImageNet categories that model was trained on:

https://deeplearning.cms.waikato.ac.nz/user-guide/class-maps/IMAGENET/

Deduce mapping between pretrained labels and dataset labels.

In [20]:
label_rename = {
    "pencilcase": "pencil case",
    "ringbinder": "ring binder",
    "soapdispenser": "dispenser",
    "bodylotion": "lotion",
    "ovenglove": "glove",
    "sodabottle": "soda",
    "mouse": "computer mouse"
    }

model_id_label = model.config.id2label

model_label_id = {v: k for k, v in model.config.id2label.items()}

ds_labels = dataset["train"].features["label"].names

print(ds_labels)

ds_labels = tuple(map(
    lambda label: label_rename[label] if label in label_rename.keys() else label,
    ds_labels
))


print(ds_labels)

ds_id_label = {i: label for i, label in enumerate(ds_labels)}

ds_label_id = {label: i for i, label in ds_id_label.items()}

print(model_id_label)
print(model_label_id)
print(ds_id_label)
print(ds_label_id)

ds_model_id_map = {}

ds_model_label_map = {}

for id, label in ds_id_label.items():

  for label_match in tuple(filter(lambda x: label in x, model_label_id.keys())):

    ds_model_label_map[label] = label_match

    ds_model_id_map[id] = model_label_id[label_match]


print(ds_model_id_map)
print(ds_model_label_map)

['book', 'cellphone', 'mouse', 'pencilcase', 'ringbinder']
('book', 'cellphone', 'computer mouse', 'pencil case', 'ring binder')

Run all data through model and check for accurate predictions, calculate F1 score.

In [21]:
model_ds_id_map = {label: i for i, label in ds_model_id_map.items()}

print(model_ds_id_map)

##  Reserve class 0 for y_hats that do not match any class.

n = len(ds_id_label.keys()) + 1

##  m = len(model_id_label.keys())

f1_matrix = [[0 for _ in range(n)] for _ in range(n)]

print(f1_matrix)

image_benchmark = Image.open(requests.get(url, stream=True).raw)

print(image_benchmark)

print(ds_split["test"])

y_hat_set = []

y_set = []

{921: 0, 487: 1, 673: 2, 709: 3}
[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=640x480 at 0x7D2744DC8D10>
Dataset({
    features: ['image', 'label'],
    num_rows: 38984
})

## **Experiment #1**

In [22]:
def test_model(model, testset, ds_model_id_map, model_ds_id_map, n):

  y_set, y_hat_set = [], []

  x = 0

  for img in testset:

    if x == 1000:

      break

    print(img)

    y = img["label"]

    if y in ds_model_id_map.keys():

      x += 1

      ##  print(ds_model_id_map[y])

      inputs = processor(img["image"], return_tensors = "pt")

      outputs = model(**inputs)

      logits = outputs.logits

      predicted_class_idx = logits.argmax(-1).item()

      ##  Convert to y_hat via dataset category id.

      if predicted_class_idx not in model_ds_id_map.keys():

          y_hat = n - 1

      else:

          y_hat = model_ds_id_map[predicted_class_idx]

      ##  f1_matrix[y_hat][y] += 1

      y_hat_set = y_hat_set + [y_hat]

      y_set = y_set + [y]

      print(f"{x}\t{y}\t{y_hat}")

  return y_set, y_hat_set

In [23]:
import numpy as np
from sklearn.metrics import f1_score, classification_report

def calc_f1(y_set: list[int], y_hat_set: list[int]):

  f1 = f1_score(y_set, y_hat_set, average=None)

  f1_weighted = f1_score(y_set, y_hat_set, average="weighted")

  print(f1)

  print(f1_weighted)

  return f1, f1_weighted

New dataset, pretrained model, no finetuning.

In [24]:
experiment_1_done = True

if experiment_1_done == False:

  y_set, y_hat_set = test_model(model,
                                ds_split["test"],
                                ds_model_id_map,
                                model_ds_id_map,
                                len(ds_id_label.keys()) + 1)

  calc_f1(y_set, y_hat_set)

## **Experiment #2**

New dataset, pretrained model, finetuning experimenting.

In [25]:
print(dataset["train"][0])
print(dataset["train"])

{'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FD4EC0>, 'label': 3}
Dataset({
    features: ['image', 'label'],
    num_rows: 194918
})

In [48]:
def create_iterator(start_val):

  counter = start_val

  def incrementer():
      nonlocal counter
      counter += 1
      return counter

  return incrementer


def transform_img(examples):

  ##  print(examples)

  print(train_iter())

  ##  Convert image format to tensor format, accepted by training process.

  inputs = processor(
      [img.convert("RGB") for img in examples["image"]],
      return_tensors = "pt"
      )

  inputs["labels"] = examples["label"]

  return inputs


def transform_label(examples):

  ##  print('examples', examples)

  ##  Convert labels to ImageNet equivalents.

  new_labels = list(map(
      lambda l: ds_model_id_map[l] if l in ds_model_id_map else 1,
      examples["label"]
  ))

  ##  print(examples["label"])

  ##  print(new_labels)

  inputs["labels"] = new_labels

  return inputs

Filter iCub World dataset to retrieve only data points for which a corresponding label exists in the original ImageNet dataset the model was trained on. This prevents the training of data for which no corresponding class exists.

In [28]:
#ds_subset_filtered = dataset_filtered["train"].train_test_split(
#  test_size = 0.2,
#  stratify_by_column = "label"
#  seed = 6948566879846,
#)

##  Trains OK.
#ds_subset_train_img = ds_subset["train"].with_transform(transform_img)
#ds_subset_test_img = ds_subset["test"].with_transform(transform_img)

##  Trains OK.
#ds_subset_filt_train_img = ds_subset_filtered["train"].with_transform(transform_img)
#ds_subset_filt_test_img = ds_subset_filtered["test"].with_transform(transform_img)

In [27]:
dataset_filtered = dataset.filter(lambda d: d["label"] in ds_model_id_map.keys())

Filter:   0%|          | 0/194918 [00:00<?, ? examples/s]

                                                                               image  \
0  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB4890>
1  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB56A0>
2  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB5400>
3  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB77D0>
4  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB5BB0>
5  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB7B60>
6  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB54C0>
7  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB7E00>
8  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB6000>
9  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779FB7770>

   label
0      3
1      3
2      1
3      3
4      0
5      2
6      1
7      0
8      2
9      0

Adjust the labels of the data to match the ImageNet dataset.

Also run the images through the image processor.

In [40]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

print(pd.DataFrame(dataset_filtered["train"].shuffle(seed=3954385)[:10]))

print(dataset_filtered)

                                                                               image  \
0  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C15D30>
1  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C15700>
2  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C14170>
3  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C17740>
4  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C173B0>
5  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C17560>
6  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C17D70>
7  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C165A0>
8  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C16900>
9  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x7D2779C17A10>

   label
0      3
1      3
2      1
3      3
4      0
5      2
6      1
7      0
8      2
9      0
DatasetDict({
    train: Dataset({
        features: ['image', 'label'],
        num_rows: 159853
    })
})

In [42]:
ds_subset_filtered = dataset_filtered["train"].train_test_split(
  #train_size = 20,
  test_size = 0.2,
  seed = 6948566879846,
  stratify_by_column = "label"
)

DatasetDict({
    train: Dataset({
        features: ['image', 'label'],
        num_rows: 159853
    })
})

In [52]:
##  OK as of 19/03/2026 10:41am.
ds_subset_filt_train_img_relabel = ds_subset_filtered["train"].with_transform(transform_img).with_transform(transform_label)

##  Split again for validation and test sets.
ds_subset_filt_testvalid_img_relabel = ds_subset_filtered["test"].train_test_split(
  train_size = 0.5,
  test_size = 0.5,
  seed = 6948566879846,
  stratify_by_column = "label"
)

ds_subset_filt_validation_img_relabel = ds_subset_filt_testvalid_img_relabel["train"].with_transform(transform_img).with_transform(transform_label)

print(dataset_filtered)

DatasetDict({
    train: Dataset({
        features: ['image', 'label'],
        num_rows: 159853
    })
})

In [82]:
print(ds_subset_filt_train_img_relabel)

Dataset({
    features: ['image', 'label'],
    num_rows: 127882
})

Fine-tune model. Note that the HuggingFace library will default to GPU.

In [53]:
from transformers import TrainingArguments, Trainer

import torch

##  print(ds_split["train"][0])

train_iter = create_iterator(0)

model_ex_2 = ViTForImageClassification.from_pretrained(
    'google/vit-base-patch16-224'
)

training_args = TrainingArguments(
    output_dir = "/content/model_ex_2",
    num_train_epochs = 8,               ##  Frequency of times to feed training data.
    per_device_train_batch_size = 256,  ##  Batch size when training.
    gradient_accumulation_steps = 8,    ##  Delay before backpropagation.
    gradient_checkpointing = True,      ##  More on-the-fly during backpropagation.
    learning_rate = 2e-5,               ##  The rate of parameter iteration.
    logging_steps = 10,                 ##  How often to update loss function.
    eval_strategy = "epoch",            ##  Run evaluation at end of epoch.
    save_strategy = "epoch",            ##  Save at end of each epoch.
    load_best_model_at_end = True,      ##  Load best model at end, via evaluations.
    remove_unused_columns = False,
)

trainer = Trainer(
    model = model_ex_2,
    args = training_args,
    train_dataset = ds_subset_filt_train_img_relabel,
    eval_dataset = ds_subset_filt_validation_img_relabel,
    ##  processing_class = tokenizer,
    ##  data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

print("Training with device:", trainer.args.device)

experiment_2_train_done = True

if experiment_2_train_done == False:

  trainer.train()

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

Training with device: cuda:0

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=504, training_loss=1.5402600528701904, metrics={'train_runtime': 1392.3155, 'train_samples_per_second': 734.787, 'train_steps_per_second': 0.362, 'total_flos': 3.12740546936832e+17, 'train_loss': 1.5402600528701904, 'epoch': 8.0})

In [ ]:
import matplotlib.pyplot as plt

# 1. Convert log history to a Pandas DataFrame
history = pd.DataFrame(trainer.state.log_history)

# 2. Separate training and evaluation logs
# Training logs usually have 'loss', eval logs have 'eval_loss'
train_loss = history[history['loss'].notna()]
eval_loss = history[history['eval_loss'].notna()]

plt.figure(figsize=(10, 5))

# Plotting Training Loss
plt.plot(train_loss['epoch'], train_loss['loss'], label='Training Loss', marker='o')

# Plotting Evaluation Loss
plt.plot(eval_loss['epoch'], eval_loss['eval_loss'], label='Evaluation Loss', marker='s')

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()
plt.savefig("ex_2_loss_func.pdf", format="pdf")

In [58]:
def transform_label_v2(examples):

  new_labels = list(map(
      lambda l: ds_model_id_map[l] if l in ds_model_id_map else 1,
      examples["label"]
  ))

  updated_examples = {
      "labels": new_labels,
      "image": examples["image"]
  }

  if 'pixel_values' in examples:
      updated_examples['pixel_values'] = examples['pixel_values']

  return updated_examples


##print(pd.DataFrame(ds_subset_filt_test_img_relabel_v3[:10]))

DatasetDict({
    train: Dataset({
        features: ['image', 'label'],
        num_rows: 159853
    })
})

In [62]:
from transformers import pipeline

##  print(ds_model_id_map)


def data_generator(testset):
    for sample in testset:
        # For ViT, we yield the PIL image object directly
        yield sample["image"]


def test_model_ex_2(m_classifier, processor, testset):

  y_set, y_hat_set = [], []

  pipe = pipeline(
      "image-classification",
      model = m_classifier,
      image_processor = processor,
      torch_dtype = torch.float16
      )

  for i, out in enumerate(pipe(data_generator(testset), batch_size=256)):

    y_hat_label = out[0]['label']

    y_hat = pipe.model.config.label2id[y_hat_label]

    y = testset[i]['labels']

    print(i)

    ##  print(y_hat, y)

    print(y, y_hat)

    y_set = y_set + [y]

    y_hat_set = y_hat_set + [y_hat]

  return y_set, y_hat_set


ds_subset_filt_test_img_relabel = ds_subset_filt_testvalid_img_relabel["test"].with_transform(transform_label_v2)

print(dataset_filtered)


experiment_2_test_done = True

if experiment_2_test_done == False:

  y_set, y_hat_set = test_model_ex_2(
      model_ex_2,
      ViTImageProcessor.from_pretrained('google/vit-base-patch16-224'),
      ds_subset_filt_test_img_relabel
      )

  f1_each, f1_weighted = calc_f1(y_set, y_hat_set)

Streaming output truncated to the last 5000 lines.
13503
673 446
13504
709 446
13505
709 446
13506
709 673
13507
709 610
13508
673 446
13509
921 446
13510
487 446
13511
709 527
13512
673 834
13513
487 446
13514
487 667
13515
921 587
13516
921 681
13517
673 446
13518
921 788
13519
709 893
13520
921 620
13521
673 593
13522
487 446
13523
487 446
13524
709 624
13525
921 673
13526
709 860
13527
487 446
13528
921 624
13529
487 673
13530
709 446
13531
921 527
13532
709 446
13533
921 624
13534
709 446
13535
673 446
13536
709 446
13537
673 446
13538
487 446
13539
921 526
13540
709 624
13541
487 590
13542
921 624
13543
487 527
13544
709 542
13545
921 446
13546
487 921
13547
673 620
13548
709 681
13549
487 446
13550
487 620
13551
921 446
13552
487 921
13553
487 549
13554
709 673
13555
673 542
13556
921 673
13557
709 549
13558
487 624
13559
673 620
13560
709 527
13561
487 921
13562
487 699
13563
709 921
13564
921 446
13565
673 446
13566
921 709
13567
487 673
13568
487 620
13569
921 673
13570
673 667
13571
921 446
13572
487 590
13573
487 921
13574
921 848
13575
921 860
13576
921 620
13577
487 400
13578
709 551
13579
487 446
13580
673 526
13581
487 446
13582
709 921
13583
673 446
13584
709 527
13585
921 763
13586
921 446
13587
487 413
13588
921 446
13589
673 446
13590
709 620
13591
921 446
13592
487 526
13593
487 446
13594
921 673
13595
709 688
13596
921 620
13597
487 446
13598
673 446
13599
709 681
13600
673 526
13601
487 893
13602
921 446
13603
673 526
13604
673 590
13605
487 662
13606
709 917
13607
487 446
13608
487 845
13609
709 917
13610
921 624
13611
673 917
13612
673 917
13613
921 446
13614
673 620
13615
673 921
13616
921 681
13617
673 401
13618
921 526
13619
487 620
13620
709 673
13621
673 851
13622
709 882
13623
673 917
13624
921 620
13625
673 673
13626
487 549
13627
709 673
13628
673 446
13629
673 769
13630
709 446
13631
673 673
13632
673 673
13633
673 446
13634
709 446
13635
673 886
13636
709 699
13637
709 543
13638
487 893
13639
673 673
13640
673 527
13641
921 624
13642
673 526
13643
709 940
13644
673 743
13645
921 446
13646
921 699
13647
487 446
13648
487 446
13649
673 590
13650
487 446
13651
709 788
13652
673 613
13653
921 673
13654
709 673
13655
487 921
13656
487 624
13657
673 526
13658
921 446
13659
921 590
13660
673 752
13661
673 549
13662
921 446
13663
921 624
13664
673 446
13665
487 446
13666
673 761
13667
673 636
13668
921 446
13669
673 446
13670
709 446
13671
487 526
13672
709 620
13673
921 610
13674
673 446
13675
921 673
13676
921 446
13677
487 673
13678
673 747
13679
921 620
13680
921 446
13681
921 527
13682
487 620
13683
709 673
13684
673 620
13685
921 446
13686
487 446
13687
921 549
13688
709 737
13689
487 851
13690
709 848
13691
921 446
13692
487 446
13693
487 620
13694
709 788
13695
673 446
13696
487 549
13697
921 624
13698
673 921
13699
921 620
13700
709 487
13701
487 624
13702
673 851
13703
487 446
13704
673 772
13705
673 446
13706
673 673
13707
673 893
13708
487 590
13709
673 549
13710
487 446
13711
487 446
13712
921 446
13713
921 446
13714
921 526
13715
673 673
13716
487 549
13717
487 624
13718
673 446
13719
673 487
13720
673 921
13721
921 446
13722
709 906
13723
709 917
13724
673 673
13725
487 610
13726
921 673
13727
709 526
13728
487 549
13729
673 921
13730
487 526
13731
673 808
13732
673 678
13733
673 769
13734
921 446
13735
673 620
13736
673 549
13737
709 446
13738
673 624
13739
921 446
13740
673 496
13741
487 446
13742
673 446
13743
487 590
13744
709 446
13745
673 673
13746
487 446
13747
709 917
13748
921 446
13749
921 764
13750
709 851
13751
673 921
13752
709 624
13753
921 673
13754
709 673
13755
673 624
13756
709 752
13757
921 713
13758
921 526
13759
709 589
13760
921 549
13761
709 921
13762
487 446
13763
673 673
13764
673 526
13765
673 584
13766
673 624
13767
709 610
13768
487 590
13769
709 526
13770
709 681
13771
673 620
13772
487 549
13773
921 624
13774
709 620
13775
709 662
13776
673 622
13777
709 620
13778
487 548
13779
487 699
13780
709 673
13781
487 446
13782
709 777
13783
709 681
13784
673 624
13785
709 921
13786
709 681
13787
921 446
13788
921 624
13789
487 446
13790
673 880
13791
709 526
13792
673 526
13793
709 673
13794
921 446
13795
921 570
13796
673 740
13797
709 446
13798
487 859
13799
709 673
13800
673 446
13801
487 624
13802
709 769
13803
921 610
13804
921 446
13805
921 917
13806
921 681
13807
487 917
13808
921 526
13809
709 401
13810
673 446
13811
921 860
13812
921 673
13813
921 921
13814
709 921
13815
709 549
13816
487 617
13817
487 620
13818
709 446
13819
921 893
13820
673 921
13821
487 446
13822
673 624
13823
709 921
13824
921 570
13825
921 921
13826
709 662
13827
709 446
13828
673 446
13829
487 624
13830
673 446
13831
921 673
13832
487 549
13833
673 662
13834
709 678
13835
673 418
13836
673 673
13837
709 673
13838
487 692
13839
487 446
13840
709 921
13841
673 673
13842
921 662
13843
709 624
13844
487 446
13845
709 446
13846
921 921
13847
673 446
13848
673 921
13849
709 921
13850
709 860
13851
709 526
13852
673 523
13853
709 450
13854
709 673
13855
709 446
13856
673 526
13857
709 446
13858
921 624
13859
487 662
13860
487 713
13861
487 917
13862
673 673
13863
673 446
13864
921 752
13865
709 681
13866
921 446
13867
709 613
13868
709 769
13869
709 655
13870
673 446
13871
921 446
13872
709 747
13873
673 446
13874
673 662
13875
673 769
13876
673 921
13877
921 624
13878
921 446
13879
709 688
13880
709 446
13881
921 893
13882
921 526
13883
709 921
13884
673 681
13885
921 713
13886
487 446
13887
487 921
13888
487 558
13889
709 673
13890
673 673
13891
921 446
13892
921 446
13893
921 681
13894
673 673
13895
673 860
13896
673 624
13897
487 917
13898
673 526
13899
487 590
13900
673 624
13901
921 446
13902
921 446
13903
487 526
13904
673 526
13905
487 446
13906
709 921
13907
921 678
13908
673 593
13909
487 446
13910
487 446
13911
487 487
13912
673 624
13913
709 860
13914
673 624
13915
921 699
13916
487 446
13917
921 446
13918
921 624
13919
921 851
13920
487 681
13921
487 917
13922
921 527
13923
487 446
13924
709 733
13925
921 851
13926
487 446
13927
709 446
13928
673 446
13929
709 610
13930
673 523
13931
709 630
13932
709 898
13933
487 526
13934
673 917
13935
921 848
13936
487 446
13937
921 617
13938
673 401
13939
487 713
13940
921 769
13941
487 549
13942
487 481
13943
673 681
13944
673 526
13945
673 610
13946
673 446
13947
673 610
13948
673 446
13949
673 673
13950
921 743
13951
921 446
13952
673 526
13953
673 446
13954
921 610
13955
673 921
13956
709 681
13957
673 921
13958
709 673
13959
673 620
13960
709 673
13961
921 446
13962
921 446
13963
673 446
13964
709 401
13965
921 446
13966
487 446
13967
673 624
13968
921 673
13969
709 606
13970
487 893
13971
921 681
13972
709 446
13973
487 527
13974
921 446
13975
673 401
13976
921 620
13977
709 673
13978
487 446
13979
673 684
13980
673 446
13981
673 446
13982
709 662
13983
921 446
13984
921 624
13985
709 681
13986
709 480
13987
673 526
13988
921 526
13989
709 788
13990
709 624
13991
921 893
13992
673 620
13993
673 921
13994
921 681
13995
673 446
13996
709 446
13997
487 620
13998
921 917
13999
487 624
14000
487 446
14001
709 446
14002
487 662
14003
673 681
14004
709 527
14005
921 624
14006
921 446
14007
487 624
14008
673 480
14009
673 543
14010
709 593
14011
709 558
14012
709 446
14013
673 446
14014
921 446
14015
673 673
14016
487 446
14017
709 610
14018
709 811
14019
487 745
14020
921 851
14021
921 681
14022
673 681
14023
709 921
14024
709 624
14025
673 438
14026
673 446
14027
921 446
14028
921 747
14029
921 921
14030
709 681
14031
487 620
14032
673 518
14033
921 590
14034
673 446
14035
487 673
14036
921 681
14037
673 624
14038
709 808
14039
487 446
14040
921 446
14041
709 620
14042
921 446
14043
487 446
14044
673 446
14045
709 851
14046
487 788
14047
673 620
14048
673 446
14049
921 921
14050
673 593
14051
487 921
14052
487 662
14053
709 638
14054
487 446
14055
673 446
14056
921 446
14057
709 636
14058
709 788
14059
673 446
14060
709 624
14061
709 446
14062
709 610
14063
709 446
14064
921 446
14065
673 446
14066
709 673
14067
921 921
14068
921 921
14069
673 917
14070
921 921
14071
673 446
14072
921 610
14073
709 673
14074
709 681
14075
487 673
14076
673 446
14077
673 662
14078
487 624
14079
921 446
14080
487 446
14081
487 624
14082
673 841
14083
487 796
14084
487 917
14085
709 606
14086
709 681
14087
673 446
14088
487 446
14089
487 422
14090
921 593
14091
709 673
14092
921 620
14093
487 446
14094
921 893
14095
487 446
14096
673 526
14097
487 446
14098
673 699
14099
921 446
14100
921 526
14101
709 446
14102
673 446
14103
921 673
14104
709 673
14105
487 624
14106
673 481
14107
673 713
14108
921 620
14109
673 673
14110
709 662
14111
921 549
14112
673 543
14113
487 549
14114
921 585
14115
921 662
14116
709 624
14117
921 673
14118
673 699
14119
673 446
14120
673 446
14121
921 681
14122
673 446
14123
921 527
14124
709 788
14125
487 681
14126
709 655
14127
673 620
14128
673 527
14129
709 527
14130
673 662
14131
673 446
14132
921 401
14133
709 446
14134
673 543
14135
673 527
14136
921 446
14137
673 453
14138
487 401
14139
673 526
14140
921 446
14141
709 692
14142
487 613
14143
921 713
14144
921 921
14145
673 526
14146
921 624
14147
673 446
14148
673 860
14149
921 699
14150
673 917
14151
921 446
14152
921 446
14153
921 713
14154
487 917
14155
709 527
14156
673 446
14157
921 446
14158
673 624
14159
673 620
14160
673 446
14161
487 624
14162
487 446
14163
921 769
14164
709 678
14165
709 613
14166
487 549
14167
921 549
14168
487 678
14169
921 673
14170
487 893
14171
709 673
14172
487 624
14173
673 624
14174
673 446
14175
921 446
14176
487 624
14177
709 526
14178
487 446
14179
709 624
14180
709 610
14181
487 499
14182
709 917
14183
921 624
14184
921 446
14185
487 526
14186
673 549
14187
921 446
14188
673 527
14189
921 851
14190
673 590
14191
487 446
14192
921 446
14193
673 610
14194
673 917
14195
709 549
14196
921 681
14197
673 526
14198
709 624
14199
673 673
14200
487 446
14201
709 673
14202
709 681
14203
709 399
14204
673 769
14205
487 446
14206
921 446
14207
487 446
14208
673 481
14209
709 401
14210
673 446
14211
921 620
14212
709 543
14213
673 917
14214
921 921
14215
487 446
14216
487 917
14217
921 673
14218
487 745
14219
487 446
14220
673 624
14221
487 446
14222
673 624
14223
673 808
14224
921 446
14225
921 917
14226
673 526
14227
921 446
14228
487 796
14229
673 446
14230
673 713
14231
487 624
14232
487 446
14233
673 446
14234
709 590
14235
487 446
14236
709 921
14237
487 446
14238
921 446
14239
673 549
14240
709 446
14241
921 446
14242
709 681
14243
709 415
14244
709 673
14245
673 446
14246
921 681
14247
709 526
14248
673 606
14249
709 788
14250
673 589
14251
673 620
14252
673 921
14253
673 673
14254
673 917
14255
487 624
14256
921 673
14257
709 446
14258
921 917
14259
921 681
14260
673 681
14261
921 673
14262
709 673
14263
709 446
14264
673 731
14265
709 446
14266
709 769
14267
673 673
14268
673 624
14269
709 917
14270
487 446
14271
921 620
14272
921 624
14273
709 446
14274
673 673
14275
709 692
14276
487 446
14277
487 446
14278
673 620
14279
709 673
14280
709 662
14281
487 860
14282
921 713
14283
921 446
14284
921 673
14285
487 624
14286
921 446
14287
709 673
14288
673 851
14289
921 624
14290
487 851
14291
673 851
14292
921 620
14293
487 796
14294
709 617
14295
709 673
14296
709 624
14297
921 681
14298
487 446
14299
673 446
14300
487 446
14301
487 681
14302
709 681
14303
709 678
14304
921 446
14305
673 526
14306
673 921
14307
921 681
14308
673 526
14309
921 526
14310
709 662
14311
673 917
14312
921 921
14313
673 921
14314
673 543
14315
673 673
14316
709 446
14317
921 624
14318
709 921
14319
709 673
14320
709 673
14321
709 446
14322
921 446
14323
487 446
14324
709 747
14325
921 606
14326
487 446
14327
487 620
14328
673 673
14329
921 446
14330
921 917
14331
709 673
14332
487 548
14333
673 499
14334
487 446
14335
921 893
14336
921 624
14337
921 681
14338
487 611
14339
673 593
14340
709 921
14341
487 624
14342
673 606
14343
673 446
14344
709 673
14345
921 624
14346
673 598
14347
673 624
14348
673 673
14349
673 713
14350
673 446
14351
487 709
14352
487 624
14353
673 796
14354
673 769
14355
921 917
14356
673 624
14357
709 624
14358
487 446
14359
673 610
14360
921 526
14361
709 921
14362
487 620
14363
487 921
14364
487 446
14365
709 446
14366
673 851
14367
709 487
14368
673 763
14369
709 917
14370
921 921
14371
487 921
14372
921 860
14373
921 836
14374
921 681
14375
709 681
14376
709 446
14377
921 527
14378
673 549
14379
673 681
14380
709 702
14381
673 613
14382
921 917
14383
709 543
14384
487 446
14385
487 446
14386
487 446
14387
487 526
14388
921 446
14389
673 713
14390
921 624
14391
921 611
14392
673 673
14393
487 743
14394
487 624
14395
709 446
14396
709 673
14397
487 446
14398
673 446
14399
487 851
14400
673 543
14401
709 624
14402
709 624
14403
487 446
14404
487 446
14405
921 681
14406
921 624
14407
709 446
14408
673 747
14409
487 446
14410
921 446
14411
709 450
14412
673 673
14413
673 688
14414
921 917
14415
921 681
14416
673 769
14417
487 446
14418
921 917
14419
921 610
14420
921 527
14421
709 480
14422
709 673
14423
709 840
14424
673 921
14425
487 446
14426
921 446
14427
487 624
14428
709 836
14429
487 681
14430
487 446
14431
673 593
14432
487 446
14433
673 624
14434
673 624
14435
673 673
14436
921 860
14437
709 487
14438
921 860
14439
921 673
14440
673 617
14441
709 606
14442
487 921
14443
709 620
14444
921 636
14445
921 620
14446
487 446
14447
921 549
14448
487 851
14449
487 662
14450
921 610
14451
709 473
14452
921 673
14453
709 921
14454
673 527
14455
921 620
14456
673 446
14457
709 620
14458
921 527
14459
673 549
14460
487 446
14461
487 504
14462
709 673
14463
673 624
14464
487 446
14465
709 620
14466
921 917
14467
921 917
14468
709 518
14469
709 418
14470
487 446
14471
709 590
14472
673 481
14473
709 673
14474
709 610
14475
673 446
14476
921 921
14477
673 683
14478
921 446
14479
673 917
14480
673 523
14481
921 446
14482
673 921
14483
487 848
14484
921 446
14485
921 593
14486
673 673
14487
487 624
14488
921 446
14489
921 624
14490
709 446
14491
709 624
14492
921 446
14493
921 446
14494
487 620
14495
487 446
14496
921 764
14497
673 921
14498
673 673
14499
673 796
14500
673 590
14501
921 446
14502
673 590
14503
487 743
14504
709 709
14505
709 526
14506
709 446
14507
673 906
14508
709 615
14509
487 549
14510
921 673
14511
487 446
14512
921 818
14513
673 593
14514
673 593
14515
921 673
14516
921 834
14517
673 413
14518
709 590
14519
673 921
14520
709 673
14521
487 499
14522
673 624
14523
921 422
14524
487 673
14525
673 673
14526
921 769
14527
673 446
14528
487 921
14529
673 681
14530
921 613
14531
673 446
14532
673 624
14533
673 713
14534
709 465
14535
921 446
14536
921 526
14537
673 921
14538
709 610
14539
673 491
14540
673 893
14541
673 527
14542
673 446
14543
709 590
14544
673 446
14545
921 446
14546
487 796
14547
709 504
14548
673 624
14549
487 446
14550
487 662
14551
921 624
14552
487 620
14553
921 662
14554
673 921
14555
921 851
14556
673 624
14557
709 921
14558
921 624
14559
709 699
14560
921 526
14561
709 919
14562
673 673
14563
487 487
14564
673 917
14565
921 769
14566
487 731
14567
487 606
14568
487 446
14569
709 613
14570
673 624
14571
921 921
14572
921 446
14573
487 446
14574
487 446
14575
487 446
14576
673 446
14577
673 446
14578
673 620
14579
487 620
14580
673 446
14581
921 681
14582
709 699
14583
487 446
14584
709 681
14585
921 446
14586
487 549
14587
487 446
14588
487 917
14589
673 673
14590
487 624
14591
921 851
14592
487 446
14593
673 446
14594
673 673
14595
709 446
14596
709 620
14597
921 446
14598
921 446
14599
921 401
14600
921 446
14601
487 446
14602
673 446
14603
487 446
14604
673 921
14605
921 446
14606
709 851
14607
673 673
14608
487 673
14609
673 921
14610
709 620
14611
673 917
14612
673 921
14613
673 624
14614
673 590
14615
709 921
14616
709 845
14617
709 673
14618
921 558
14619
487 446
14620
673 401
14621
921 527
14622
487 446
14623
709 851
14624
921 673
14625
673 446
14626
673 446
14627
921 662
14628
487 620
14629
921 624
14630
487 549
14631
709 453
14632
673 549
14633
709 526
14634
673 917
14635
673 526
14636
673 745
14637
709 713
14638
921 606
14639
921 446
14640
709 673
14641
921 446
14642
673 769
14643
921 446
14644
709 917
14645
921 446
14646
487 446
14647
921 527
14648
709 446
14649
487 851
14650
709 681
14651
709 526
14652
673 446
14653
921 446
14654
673 446
14655
921 446
14656
487 673
14657
709 681
14658
709 507
14659
921 438
14660
709 499
14661
709 446
14662
921 766
14663
673 664
14664
487 446
14665
921 446
14666
487 401
14667
921 860
14668
673 446
14669
673 673
14670
709 446
14671
921 446
14672
487 480
14673
673 673
14674
487 921
14675
673 446
14676
921 446
14677
673 893
14678
709 608
14679
921 772
14680
921 446
14681
709 841
14682
709 769
14683
921 465
14684
921 446
14685
921 446
14686
921 681
14687
487 921
14688
921 446
14689
709 526
14690
673 548
14691
709 624
14692
487 624
14693
487 446
14694
709 446
14695
921 527
14696
487 610
14697
921 681
14698
709 624
14699
709 921
14700
709 691
14701
487 438
14702
487 745
14703
487 398
14704
673 523
14705
709 673
14706
487 446
14707
921 662
14708
921 624
14709
673 673
14710
709 673
14711
709 526
14712
487 624
14713
921 446
14714
921 446
14715
709 446
14716
487 893
14717
487 624
14718
673 527
14719
921 713
14720
709 446
14721
487 921
14722
709 602
14723
921 526
14724
487 921
14725
709 709
14726
673 401
14727
487 769
14728
673 446
14729
921 549
14730
673 526
14731
709 446
14732
673 446
14733
921 921
14734
673 543
14735
487 446
14736
673 731
14737
709 446
14738
673 807
14739
487 620
14740
487 446
14741
673 438
14742
487 917
14743
487 526
14744
487 446
14745
673 921
14746
673 624
14747
921 624
14748
487 446
14749
709 620
14750
921 620
14751
709 907
14752
709 446
14753
921 558
14754
487 851
14755
673 446
14756
921 610
14757
487 446
14758
487 446
14759
673 673
14760
673 662
14761
709 681
14762
673 446
14763
487 624
14764
487 446
14765
921 526
14766
709 610
14767
487 624
14768
709 446
14769
921 438
14770
487 713
14771
709 446
14772
673 624
14773
673 673
14774
921 620
14775
673 446
14776
921 880
14777
709 893
14778
673 446
14779
673 590
14780
921 713
14781
487 893
14782
709 446
14783
709 681
14784
487 673
14785
709 921
14786
487 650
14787
921 620
14788
921 549
14789
673 446
14790
921 624
14791
921 549
14792
487 446
14793
673 713
14794
921 673
14795
673 446
14796
709 527
14797
673 921
14798
709 446
14799
921 681
14800
921 917
14801
487 624
14802
673 399
14803
487 446
14804
709 673
14805
921 731
14806
487 624
14807
709 446
14808
673 728
14809
709 610
14810
921 446
14811
921 523
14812
673 921
14813
673 624
14814
921 499
14815
921 917
14816
673 620
14817
673 673
14818
673 446
14819
709 613
14820
709 673
14821
673 620
14822
921 624
14823
709 681
14824
921 546
14825
673 446
14826
921 624
14827
921 446
14828
673 549
14829
487 624
14830
921 921
14831
921 438
14832
487 446
14833
921 917
14834
921 921
14835
709 620
14836
487 917
14837
709 673
14838
709 662
14839
921 681
14840
709 673
14841
673 446
14842
921 446
14843
709 681
14844
921 761
14845
673 558
14846
921 620
14847
709 446
14848
709 921
14849
673 526
14850
709 606
14851
673 558
14852
673 526
14853
487 624
14854
487 624
14855
487 446
14856
673 921
14857
487 446
14858
673 921
14859
709 624
14860
921 747
14861
673 624
14862
487 446
14863
921 699
14864
487 893
14865
487 446
14866
921 446
14867
487 446
14868
487 851
14869
487 446
14870
709 446
14871
487 446
14872
673 549
14873
673 620
14874
921 860
14875
487 917
14876
921 905
14877
921 590
14878
673 673
14879
673 610
14880
921 446
14881
921 446
14882
673 446
14883
487 549
14884
709 549
14885
673 446
14886
921 446
14887
709 446
14888
709 446
14889
673 673
14890
709 446
14891
487 921
14892
673 446
14893
709 673
14894
487 893
14895
921 743
14896
709 673
14897
487 921
14898
921 446
14899
921 610
14900
487 673
14901
487 860
14902
673 446
14903
487 624
14904
673 624
14905
673 446
14906
921 526
14907
709 446
14908
673 620
14909
709 446
14910
487 610
14911
673 446
14912
921 446
14913
921 446
14914
673 769
14915
673 446
14916
487 549
14917
487 453
14918
921 893
14919
709 411
14920
921 401
14921
673 446
14922
709 446
14923
673 620
14924
673 446
14925
487 526
14926
673 860
14927

In [63]:
f1_each, f1_weighted = calc_f1(y_set, y_hat_set)

report = classification_report(
    y_set,
    y_hat_set,
    output_dict=False
)

print(report)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.00504909 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.16431188 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.01076321 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.06999798 0.         0.         0.         0.
 0.         0.        ]
0.06631149091046648
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
         122       0.00      0.00      0.00         0
         183       0.00      0.00      0.00         0
         389       0.00      0.00      0.00         0
         395       0.00      0.00      0.00         0
         398       0.00      0.00      0.00         0
         399       0.00      0.00      0.00         0
         400       0.00      0.00      0.00         0
         401       0.00      0.00      0.00         0
         411       0.00      0.00      0.00         0
         413       0.00      0.00      0.00         0
         415       0.00      0.00      0.00         0
         418       0.00      0.00      0.00         0
         419       0.00      0.00      0.00         0
         421       0.00      0.00      0.00         0
         422       0.00      0.00      0.00         0
         432       0.00      0.00      0.00         0
         433       0.00      0.00      0.00         0
         438       0.00      0.00      0.00         0
         443       0.00      0.00      0.00         0
         446       0.00      0.00      0.00         0
         447       0.00      0.00      0.00         0
         450       0.00      0.00      0.00         0
         452       0.00      0.00      0.00         0
         453       0.00      0.00      0.00         0
         454       0.00      0.00      0.00         0
         456       0.00      0.00      0.00         0
         461       0.00      0.00      0.00         0
         464       0.00      0.00      0.00         0
         465       0.00      0.00      0.00         0
         473       0.00      0.00      0.00         0
         480       0.00      0.00      0.00         0
         481       0.00      0.00      0.00         0
         487       0.10      0.00      0.01      3474
         491       0.00      0.00      0.00         0
         496       0.00      0.00      0.00         0
         499       0.00      0.00      0.00         0
         502       0.00      0.00      0.00         0
         504       0.00      0.00      0.00         0
         507       0.00      0.00      0.00         0
         512       0.00      0.00      0.00         0
         518       0.00      0.00      0.00         0
         523       0.00      0.00      0.00         0
         526       0.00      0.00      0.00         0
         527       0.00      0.00      0.00         0
         542       0.00      0.00      0.00         0
         543       0.00      0.00      0.00         0
         545       0.00      0.00      0.00         0
         546       0.00      0.00      0.00         0
         548       0.00      0.00      0.00         0
         549       0.00      0.00      0.00         0
         551       0.00      0.00      0.00         0
         553       0.00      0.00      0.00         0
         556       0.00      0.00      0.00         0
         558       0.00      0.00      0.00         0
         570       0.00      0.00      0.00         0
         571       0.00      0.00      0.00         0
         579       0.00      0.00      0.00         0
         584       0.00      0.00      0.00         0
         585       0.00      0.00      0.00         0
         587       0.00      0.00      0.00         0
         588       0.00      0.00      0.00         0
         589       0.00      0.00      0.00         0
         590       0.00      0.00      0.00         0
         591       0.00      0.00      0.00         0
         592       0.00      0.00      0.00         0
         593       0.00      0.00      0.00         0
         598       0.00      0.00      0.00         0
         601       0.00      0.00      0.00         0
         602       0.00      0.00      0.00         0
         606       0.00      0.00      0.00         0
         608       0.00      0.00      0.00         0
         610       0.00      0.00      0.00         0
         611       0.00      0.00      0.00         0
         613       0.00      0.00      0.00         0
         614       0.00      0.00      0.00         0
         615       0.00      0.00      0.00         0
         617       0.00      0.00      0.00         0
         620       0.00      0.00      0.00         0
         622       0.00      0.00      0.00         0
         624       0.00      0.00      0.00         0
         626       0.00      0.00      0.00         0
         630       0.00      0.00      0.00         0
         632       0.00      0.00      0.00         0
         633       0.00      0.00      0.00         0
         635       0.00      0.00      0.00         0
         636       0.00      0.00      0.00         0
         638       0.00      0.00      0.00         0
         641       0.00      0.00      0.00         0
         642       0.00      0.00      0.00         0
         650       0.00      0.00      0.00         0
         651       0.00      0.00      0.00         0
         655       0.00      0.00      0.00         0
         662       0.00      0.00      0.00         0
         664       0.00      0.00      0.00         0
         667       0.00      0.00      0.00         0
         673       0.32      0.11      0.16      4281
         674       0.00      0.00      0.00         0
         678       0.00      0.00      0.00         0
         681       0.00      0.00      0.00         0
         683       0.00      0.00      0.00         0
         684       0.00      0.00      0.00         0
         686       0.00      0.00      0.00         0
         688       0.00      0.00      0.00         0
         689       0.00      0.00      0.00         0
         691       0.00      0.00      0.00         0
         692       0.00      0.00      0.00         0
         696       0.00      0.00      0.00         0
         697       0.00      0.00      0.00         0
         699       0.00      0.00      0.00         0
         702       0.00      0.00      0.00         0
         709       0.26      0.01      0.01      4002
         710       0.00      0.00      0.00         0
         712       0.00      0.00      0.00         0
         713       0.00      0.00      0.00         0
         714       0.00      0.00      0.00         0
         722       0.00      0.00      0.00         0
         728       0.00      0.00      0.00         0
         731       0.00      0.00      0.00         0
         732       0.00      0.00      0.00         0
         733       0.00      0.00      0.00         0
         737       0.00      0.00      0.00         0
         740       0.00      0.00      0.00         0
         742       0.00      0.00      0.00         0
         743       0.00      0.00      0.00         0
         745       0.00      0.00      0.00         0
         746       0.00      0.00      0.00         0
         747       0.00      0.00      0.00         0
         748       0.00      0.00      0.00         0
         752       0.00      0.00      0.00         0
         757       0.00      0.00      0.00         0
         761       0.00      0.00      0.00         0
         763       0.00      0.00      0.00         0
         764       0.00      0.00      0.00         0
         766       0.00      0.00      0.00         0
         769       0.00      0.00      0.00         0
         771       0.00      0.00      0.00         0
         772       0.00      0.00      0.00         0
         774       0.00      0.00      0.00         0
         775       0.00      0.00      0.00         0
         777       0.00      0.00      0.00         0
         782       0.00      0.00      0.00         0
         785       0.00      0.00      0.00         0
         788       0.00      0.00      0.00         0
         790       0.00      0.00      0.00         0
         796       0.00      0.00      0.00         0
         798       0.00      0.00      0.00         0
         800       0.00      0.00      0.00         0
         807       0.00      0.00      0.00         0
         808       0.00      0.00      0.00         0
         810       0.00      0.00      0.00         0
         811       0.00      0.00      0.00         0
         813       0.00      0.00      0.00         0
         818       0.00      0.00      0.00         0
         822       0.00      0.00      0.00         0
         824       0.00      0.00      0.00         0
         826       0.00      0.00      0.00         0
         834       0.00      0.00      0.00         0
         836       0.00      0.00      0.00         0
         838       0.00      0.00      0.00         0
         840       0.00      0.00      0.00         0
         841       0.00      0.00      0.00         0
         844       0.00      0.00      0.00         0
         845       0.00      0.00      0.00         0
         846       0.00      0.00      0.00         0
         848       0.00      0.00      0.00         0
         851       0.00      0.00      0.00         0
         859       0.00      0.00      0.00         0
         860       0.00      0.00      0.00         0
         862       0.00      0.00      0.00         0
         869       0.00      0.00      0.00         0
         877       0.00      0.00      0.00         0
         879       0.00      0.00      0.00         0
         880       0.00      0.00      0.00         0
         882       0.00      0.00      0.00         0
         885       0.00      0.00      0.00         0
         886       0.00      0.00      0.00         0
         891       0.00      0.00      0.00         0
         893       0.00      0.00      0.00         0
         898       0.00      0.00      0.00         0
         905       0.00      0.00      0.00         0
         906       0.00      0.00      0.00         0
         907       0.00      0.00      0.00         0
         909       0.00      0.00      0.00         0
         916       0.00      0.00      0.00         0
         917       0.00      0.00      0.00         0
         919       0.00      0.00      0.00         0
         921       0.24      0.04      0.07      4229
         932       0.00      0.00      0.00         0
         939       0.00      0.00      0.00         0
         940       0.00      0.00      0.00         0
         954       0.00      0.00      0.00         0
         966       0.00      0.00      0.00         0
         998       0.00      0.00      0.00         0

    accuracy                           0.04     15986
   macro avg       0.00      0.00      0.00     15986
weighted avg       0.24      0.04      0.07     15986

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#print(next(model.parameters()).dtype)
#for name, param in model.named_parameters():
#    print(f"Layer: {name} | Dtype: {param.dtype} | Device: {param.device}")

print(next(model_ex_2.parameters()).dtype)
for name, param in model_ex_2.named_parameters():
    print(f"Layer: {name} | Dtype: {param.dtype} | Device: {param.device}")

## **Experiment #3**

Fine-tuning class with best F1 score.

In [70]:
ds_673_filtered = dataset.filter(lambda d: d["label"] == model_ds_id_map[673])

In [71]:
ds_673_first_split = ds_673_filtered["train"].train_test_split(
  test_size = 0.2,
  seed = 6948566879846,
  stratify_by_column = "label"
)

ds_673_train = ds_673_first_split["train"].with_transform(transform_img).with_transform(transform_label)

##  Split again for validation and test sets.

ds_673_second_split = ds_673_first_split["test"].train_test_split(
  train_size = 0.5,
  test_size = 0.5,
  seed = 6948566879846,
  stratify_by_column = "label"
)

ds_673_validation = ds_673_second_split["train"].with_transform(transform_img).with_transform(transform_label)

ds_673_test = ds_673_second_split["test"].with_transform(transform_label_v2)

In [ ]:
print(ds_673_filtered)
print(ds_673_train)
print(ds_673_test)

print(pd.DataFrame(ds_673_first_split["train"].shuffle(seed=3954385)[:10]))

print(pd.DataFrame(ds_673_second_split["train"].shuffle(seed=3954385)[:10]))

In [ ]:
train_iter = create_iterator(0)

model_ex_3 = ViTForImageClassification.from_pretrained(
    'google/vit-base-patch16-224'
)

training_args_ex_3 = TrainingArguments(
    output_dir = "/content/model_ex_3",
    num_train_epochs = 32,               ##  Frequency of times to feed training data.
    per_device_train_batch_size = 16,   ##  Batch size when training.
    per_device_eval_batch_size = 4,     ##  Batch size when training.
    gradient_accumulation_steps = 32,   ##  Delay before backpropagation.
    gradient_checkpointing = True,      ##  More on-the-fly during backpropagation.
    learning_rate = 2e-5,               ##  The rate of parameter iteration.
    logging_steps = 10,                 ##  How often to update loss function.
    eval_strategy = "epoch",            ##  Run evaluation at end of epoch.
    save_strategy = "epoch",            ##  Save at end of each epoch.
    load_best_model_at_end = True,      ##  Load best model at end, via evaluations.
    remove_unused_columns = False,
)



trainer_ex_3 = Trainer(
    model = model_ex_3,
    args = training_args_ex_3,
    train_dataset = ds_673_train,
    eval_dataset = ds_673_validation,
    ##  processing_class = tokenizer,
    ##  data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

print("Training with device:", trainer.args.device)

trainer_ex_3.train()

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

Training with device: cuda:0

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## **Experiment #4**

Fine-tuning class with worst F1 score.

In [ ]:
dataset_filtered_best_f1 = dataset.filter(lambda d: d["label"] == model_ds_id_map[709])